# Generated by Django 2.0.3 on 2018-05-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20180417_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharticleuser',
            name='number_of_drafts',
            field=models.IntegerField(default=0),
        ),
    ]
