# Generated by Django 2.0.3 on 2018-05-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_sharticleuser_number_of_drafts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('author', models.CharField(max_length=512)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('image_path', models.CharField(blank=True, max_length=512, null=True)),
                ('date_last_modified', models.DateTimeField(auto_now_add=True)),
                ('number_of_comments', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
            ],
        ),
    ]
