# Generated by Django 2.0.3 on 2018-05-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='already_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.CharField(default='', max_length=4096),
        ),
    ]
