# Generated by Django 2.0.3 on 2018-06-06 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20180603_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date_last_modified',
            new_name='last_modified_date',
        ),
        migrations.RenameField(
            model_name='sharticleuser',
            old_name='date_last_modified',
            new_name='profile_last_modified_date',
        ),
        migrations.AddField(
            model_name='sharticleuser',
            name='articles_last_modified_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 6, 6, 16, 37, 30, 275148)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharticleuser',
            name='drafts_last_modified_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 6, 6, 16, 37, 54, 853806)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
