# Generated by Django 2.0.6 on 2018-07-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20180606_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.CharField(blank=True, choices=[('AI', 'Artifical Intelligence'), ('WP', 'Web Programming'), ('SE', 'Software Engineering'), ('DS', 'Data Science'), ('C', 'Cryptography')], max_length=2, null=True),
        ),
    ]
