# Generated by Django 2.0.6 on 2018-08-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField()),
                ('content', models.CharField(max_length=512)),
                ('author', models.CharField(max_length=512)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
